/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#ifndef STM32F411RE
	#define STM32F411RE
#endif
#undef G071RB

#ifdef STM32F411RE
	#define RCC_BASE_ADDR              0x40023800UL
	#define RCC_CFGR_REG_OFFSET        0x08UL
	#define RCC_CFGR_REG_ADDR          (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET )
	#define GPIOA_BASE_ADDR            0x40020000UL
#else // G071RB defines
	#define RCC_BASE_ADDR 0x40021000UL // Table 5. STM32G0x0 peripheral register boundary addresses
	#define GPIOA_BASE_ADDR 0x50000000UL // 5.4.12, GPIOA base address, GPIOAEN
	#define RCC_CFGR_REG_OFFSET 0x08UL // defined in 5.4.3
	#define RCC_APB_ENR_OFFSET 0x40UL // 5.4.15, APB peripheral clock enable register 2, RCC_APBENR2
	#define RCC_AHB_ENR_OFFSET 0x34UL // 5.4.12,  0x38UL (AHB peripheral clock enable register)
#endif
#define RCC_AHB_REG_ADDR (RCC_BASE_ADDR + RCC_AHB_ENR_OFFSET)

typedef volatile uint32_t Reg;

int main(void)
{
	Reg *pRccCfgrReg =  (Reg*) RCC_CFGR_REG_ADDR;

	#ifdef STM32F411RE

		//1. Configure the RCC_CFGR MCO1 bit fields to select HSI as clock source
		*pRccCfgrReg &= ~(0x3 << 21); //clear 21 and 22 bit positions
		//Configure MCO1 prescaler
		*pRccCfgrReg |= ( 1 << 25);
		*pRccCfgrReg |= ( 1 << 26);

		//2. Configure PA8 to AF0 mode to behave as MCO1 signal
		//a ) Enable the peripheral clock for GPIOA peripheral
		Reg *pRCCAhb1Enr = (Reg *)(RCC_BASE_ADDR + 0x30);
		*pRCCAhb1Enr |= ( 1 << 0); //Enable GPIOA peripheral clock

		//b ) Configure the mode of GPIOA pin 8 as alternate function mode
		Reg *pGPIOAModeReg = (Reg *)(GPIOA_BASE_ADDR + 00);
		*pGPIOAModeReg &= ~( 0x3 << 16); //clear
		*pGPIOAModeReg |= ( 0x2 << 16);  //set

		//c ) Configure the alternation function register to set the mode 0 for PA8
		Reg *pGPIOAAltFunHighReg = (Reg *)(GPIOA_BASE_ADDR + 0x24);
		*pGPIOAAltFunHighReg &= ~( 0xf << 0);

	#else // Table 6.4.1

		//1. Configure the RCC_CFGR MCO1 bit fields to select HSI as clock source
		*pRccCfgrReg &= ~(0x3 << 26); //clear 26 and 27 bit positions
		*pRccCfgrReg |= (0x3 << 24); // mark as one 24, 25 bit positions
		*pRccCfgrReg |= (1 << 28); // Configure MCO prescaler
		*pRccCfgrReg |= (1 << 29); // Configure MCO prescaler (clk/4)

		//2. Configure PA8 to AF0 mode to behave as MCO1 signal
		//a ) Enable the peripheral clock for GPIOA peripheral
		Reg *pRCCAhbEnr = (Reg *) (RCC_AHB_REG_ADDR); // Table 5.4.13 (AHB peripheral clock enable register)
		*pRCCAhbEnr |= (1 << 0);

		//b ) Configure the mode of GPIOA pin 8 as alternate function mode
		Reg *pGPIOAModeReg = (Reg *) (GPIOA_BASE_ADDR + 0x00); //Table 13, this is the GPIOA mode Register, 6.4.1
		*pGPIOAModeReg &= ~( 0x3 << 16); // clear, Table 6.4.12
		*pGPIOAModeReg |= (0x2 << 16); // this command sets actually the pin

		//c ) Configure the alternation function register to set the mode 0 for PA8
		Reg *pGPIOAAltFunHighReg = (Reg *)(GPIOA_BASE_ADDR + 0x24);
		*pGPIOAAltFunHighReg &= ~( 0xf << 0); // AFSEL8, set 0000 (AF0)

	#endif

	for(;;);
}
